import type { Metadata } from 'next';

import '@/styles/globals.css';

import { auth } from '@/auth';
import { GeistSans } from 'geist/font/sans';
import { SessionProvider } from 'next-auth/react';

import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang='en' className={GeistSans.className}>
      <body className='min-h-screen'>
        <SessionProvider session={session}>
          {children}
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
